### ISSUE TITLE
crash because of suggested reply buttons?

### ISSUE THREAD

**Issue by kamil-malinski** [Leask/halbot#10]
I just experienced this crash:

```console
[HAL] Prompt: Hallo!
file:///root/halbot/node_modules/utilitas/lib/bot.mjs:129
            if (data?.text && ctx.session.textButtons[data?.text]) {
                                                     ^

TypeError: Cannot read properties of undefined (reading 'ddd49ab7-2c49-ca8e-c31f-78e88137d4bb')
    at func (file:///root/halbot/node_modules/utilitas/lib/bot.mjs:129:54)
    at execute (/root/halbot/node_modules/telegraf/lib/composer.js:485:23)
    at /root/halbot/node_modules/telegraf/lib/composer.js:486:27
    at execute (/root/halbot/node_modules/telegraf/lib/composer.js:485:23)
    at /root/halbot/node_modules/telegraf/lib/composer.js:486:27
    at func (file:///root/halbot/node_modules/utilitas/lib/bot.mjs:96:15)
    at execute (/root/halbot/node_modules/telegraf/lib/composer.js:485:23)
    at /root/halbot/node_modules/telegraf/lib/composer.js:486:27
    at execute (/root/halbot/node_modules/telegraf/lib/composer.js:485:23)
    at /root/halbot/node_modules/telegraf/lib/composer.js:486:27
```

**Comment by Leask** [comment]
Oops, I need to initial the session before using it. Thanks! A quick fix is uploading.

**Comment by Leask** [comment]
Fixed. 🍻
